### ISSUE TITLE
[FR] Option to exclude titles or filenames

### ISSUE THREAD

**Issue by aarononeal** [jillro/obsidian-cards-view-plugin#11]
It is a common practice to begin markdown with a `# Title` that matches the filename. Cards View then displays this information twice because it shows the filename and then the contents of the file which includes the title. Much visual space is wasted because of this.

It would be ideal to have an option to either turn off showing the card filename or to show card content after the first `# Title`.

**Comment by matebitte** [comment]
I second this, looks very clunky with H1 headings

**Comment by aarononeal** [comment]
Thank you, this feature is great! ❤️
