### ISSUE TITLE
Card heights and embeds

### ISSUE THREAD

**Issue by huachuman** [jillro/obsidian-cards-view-plugin#13]
Any time a note has an ![[embed]] it stretches the card the full height of the embed.

Other cards seem to be so small they only display a line or two. While yet others display a little bit more reasonably.

**Comment by huachuman** [comment]
I updated the plugin and unfortunately this is still an issue. Any note with an ![[embedded]]] note will stretch the card the entire length of that note.

**Comment by jillro** [comment]
I promise it will be fixed sooner or later, I just cannot guarantee you when, because I maintain this plugin on my spare time.

**Comment by huachuman** [comment]
No worries, looking forward to using your plugin :)
