### ISSUE TITLE
Embedded or dataview content not truncated

### ISSUE THREAD

**Issue by MrBertie** [jillro/obsidian-cards-view-plugin#3]
This is a great idea, first of all thank you immensely for working on this, it has huge potential! ✨

I notice that pages with embedded or Dataview content are not truncated like normal pages, making them excessively long. Is this something you could look into?

Out of interest, how do you decide the truncated length of each page? It might be more practical for each page Card to have a similar height, right now it looks a little random.

**Comment by huachuman** [comment]
I'm experiencing the same problem

I agree that having them all the same height could be a viable fix for this. I'm hoping to some day build an Evernote-like dashboard in Obsidian where I can set rows for e.g. recent notes, notes matching a certain tag, etc.

**Comment by brendon-felix** [comment]
I agree about the potential of this plugin. Also came here to report this issue. Here is a screenshot of what I am seeing in notes with embeds.
<img width="959" alt="image" src="https://github.com/jillro/obsidian-cards-view-plugin/assets/124619546/21258a07-4e21-403c-b0e2-83fcc90267c2">
