### ISSUE TITLE
Use case is not there - I can see this being really useful though

### ISSUE THREAD

**Issue by polyinnovator** [jillro/obsidian-cards-view-plugin#7]
FIrst and foremost I was impressed by the performance how it all looked. Titles sometimes get too big (like in the doc), but that is more cause the saved article had h1 and h2 at the top of the note.

As someone who has around 5000 notes I can't see myself using this at this stage, as it just simply pulls ALL notes forward. Loaded pretty well I might add. At least for the few scrolls I did.

The problem is I could see this being useful to view certain folders. Like if I have a blog post folder and I only want to see whats in it.

Perhaps there could even be a diy version where I keep track of important notes by choosing myself what gets added. Sorta like a project page, I've seen other plugins do something like that, but its not implemented well or doesn't look good. I could see the notes cards like these really make it fit quite well.

**Comment by jillro** [comment]
Hello @polyinnovator and thanks for your comments ! I'm closing this issue as https://github.com/jillro/obsidian-cards-view-plugin/pull/36 partly fit what you describe. If you have an idea of a feature that would more fit the needs you describe here, please feel free to open a new issue on the specific feature.
